[project]
name = "wx-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.13.2",
    "fastapi[all]>=0.124.2",
    "jinja2>=3.1.6",
    "numpy>=2.3.5",
]
